# Generated by Django 2.2.12 on 2020-04-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_aplicacionesproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacionesproducto',
            name='nombre',
        ),
    ]
