# Generated by Django 2.2.12 on 2020-04-26 16:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_aplicacionesproducto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionesproducto',
            name='aplicaciones',
            field=djongo.models.fields.ArrayField(default='', model_container=models.CharField(max_length=25)),
            preserve_default=False,
        ),
    ]
