# Generated by Django 2.2.12 on 2020-04-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20200426_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AplicacionProducto',
            new_name='AccionProducto',
        ),
    ]
