# Generated by Django 2.2.12 on 2020-04-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20200426_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccionProducto',
        ),
    ]
