# Generated by Django 2.2.12 on 2020-06-10 07:25

from django.db import migrations
import djongo.models.fields
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_detalleunitario_lote_medidas_presentacion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentaciones',
            field=djongo.models.fields.ArrayField(default='', model_container=inventario.models.Presentacion),
            preserve_default=False,
        ),
    ]
